rotating_image_portlet_type = {
    'title': 'portal_type_RotatingImagePortlet_title',
    'description': 'portal_type_RotatingImagePortlet_description',
    'content_icon': 'rot_image_portlet_icon.png',
    'content_meta_type': 'CPS Portlet',
    'product': 'CPSPortlets',
    'factory': 'addCPSPortlet',
    'immediate_view': 'cpsportlet_edit_form',
    'global_allow': True,
    'filter_content_types': True,
    'allowed_content_types': (),
    'allow_discussion': False,
    'cps_is_searchable': False,
    'cps_proxy_type': '',
    'cps_display_as_document_in_listing': False,
    'cps_is_portalbox': False,
    'schemas': ('portlet_common', 'rotating_image_portlet_flexible', 'rotating_image_portlet', 'common', 'metadata'),
    'layouts': ('portlet_common', 'rotating_image_portlet_flexible', 'rotating_image_portlet'),
    'layout_clusters': ('metadata:metadata',),
    'flexible_layouts': ('rotating_image_portlet_flexible:rotating_image_portlet_flexible',),
    'storage_methods': (),
    'cps_is_portlet': True,
    'actions': (
         {'id': 'view',
          'name': 'action_view',
          'action': 'string:${object_url}/cpsportlet_view',
          'condition': '',
          'permission': ('View',),
          'category': 'object',
          'visible': True,},
         {'id': 'edit',
          'name': 'action_edit',
          'action': 'string:${object_url}/cpsportlet_edit_form',
          'condition': '',
          'permission': ('Modify portal content',),
          'category': 'object',
          'visible': True,},
         {'id': 'metadata',
          'name': 'action_metadata',
          'action': 'string:${object_url}/cpsportlet_metadata',
          'condition': '',
          'permission': ('Manage Portlets',),
          'category': 'object',
          'visible': False,},
    )
}

types = {}
types['Rotating Image Portlet'] = rotating_image_portlet_type
return types
