custom_portlet_layout = {
    'widgets': {
        'portlet': {
            'type': 'CPS Portlet Custom Widget',
            'data': {
                'title': '',
                'fields': ('portlet',),
                'is_required': 0,
                'label': '',
                'label_edit': '',
                'description': '',
                'help': '',
                'is_i18n': 0,
                'readonly_layout_modes': [],
                'hidden_layout_modes': ('edit',),
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'depends_on_field_id': '',
                'depends_on_field_value': '',
                'display_if_depends_equals': True,
                'display_width': 20,
                'size_max': 0,
            },
        },
        'render_method': {
            'type': 'String Widget',
            'data': {
                'title': '',
                'fields': ('render_method',),
                'is_required': True,
                'label': '',
                'label_edit': 'cpsportlets_custom_render_method_label',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': [],
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': [],
                'hidden_empty': 0,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'depends_on_field_id': '',
                'depends_on_field_value': '',
                'display_if_depends_equals': True,
                'display_width': 36,
                'size_max': 0,
            },
        },
        'custom_cache_params': {
            'type': 'Lines Widget',
            'data': {
                'title': '',
                'fields': ('custom_cache_params',),
                'is_required': False,
                'label': '',
                'label_edit': 'cpsportlets_common_custom_cache_params_label',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'depends_on_field_id': '',
                'depends_on_field_value': '',
                'display_if_depends_equals': True,
                'width': 40,
                'height': 5,
                'format_empty': '',
            },
        },
        'js_render_method': {
            'type': 'String Widget',
            'data': {
                'title': '',
                'fields': ('js_render_method',),
                'label_edit': 'cpsportlets_custom_js_render_method_label',
                'description': '',
                'is_i18n': True,
                'hidden_layout_modes': ('view',),
                'display_width': 36,
                'size_max': 0,
            },
        },
        'i18n': {
            'type': 'Boolean Widget',
            'data': {
                'title': '',
                'fields': ('i18n',),
                'is_required': False,
                'label': '',
                'label_edit': 'label_cpsportlets_i18n',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'label_false': 'cpsschemas_label_false',
                'label_true': 'cpsschemas_label_true',
                'render_format': 'select',
            },
        },
    },
    'layout': {
        'style_prefix': 'layout_portlet_',
        'flexible_widgets': (),
        'validate_values_expr': '',
        'ncols': 2,
        'rows': [
            [{'widget_id': 'portlet', 'ncols': 2},
            ],
            [{'widget_id': 'render_method', 'ncols': 1},
             {'widget_id': 'js_render_method', 'ncols': 1},
            ],
            [{'widget_id': 'custom_cache_params', 'ncols': 1},
             {'widget_id': 'i18n', 'ncols': 1},
            ],
        ],
    },
}


layouts = {'custom_portlet': custom_portlet_layout}
return layouts
