portlet_common_layout = {
    'widgets': {
        'Description': {
            'type': 'TextArea Widget',
            'data': {
                'title': '',
                'fields': ('Description',),
                'is_required': False,
                'label': '',
                'label_edit': 'label_description',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'widget_group_id': '',
                'depends_on_field_id': '',
                'depends_on_field_value': '',
                'display_if_depends_equals': True,
                'width': 40,
                'height': 2,
                'render_format': 'text',
            },
        },
        'Title': {
            'type': 'String Widget',
            'data': {
                'title': '',
                'fields': ('Title',),
                'is_required': True,
                'label': '',
                'label_edit': 'label_cpsportlets_title',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'widget_group_id': '',
                'depends_on_field_id': '',
                'depends_on_field_value': '',
                'display_if_depends_equals': True,
                'display_width': 36,
                'size_max': 36,
            },
        },
        'visibility_range': {
            'type': 'CPS Portlet Visibility Widget',
            'data': {
                'title': '',
                'fields': ('visibility_range',),
                'is_required': False,
                'label': '',
                'label_edit': 'cpsportlets_common_visibility_range_label',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': 'context/isGlobal',
                'css_class': '',
                'widget_mode_expr': '',
                'widget_group_id': '',
                'depends_on_field_id': '',
                'depends_on_field_value': '',
                'display_if_depends_equals': True,
                'vocabulary': 'cpsportlets_visibility_range_voc',
                'translated': True,
            },
        },
    },
    'layout': {
        'style_prefix': 'layout_portlet_',
        'flexible_widgets': (),
        'ncols': 3,
        'rows': [
            [{'widget_id': 'Title', 'ncols': 3},
            ],
            [{'widget_id': 'Description', 'ncols': 3},
            ],
            [{'widget_id': 'visibility_range', 'ncols': 3},
            ],
        ],
    },
}


layouts = {'portlet_common': portlet_common_layout}
return layouts
