search_portlet_layout = {
    'widgets': {
        'search': {
            'type': 'Generic Portlet Widget',
            'data': {
                'title': '',
                'fields': ('dummy',),
                'is_required': False,
                'label': '',
                'label_edit': '',
                'description': '',
                'help': '',
                'is_i18n': False,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('edit',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'render_method': 'widget_portlet_search',
                'field_types': ('CPS String Field',),
            },
        },
        'advanced_search_link': {
            'type': 'CheckBox Widget',
            'data': {
                'title': '',
                'fields': ('advanced_search_link',),
                'is_required': False,
                'label': '',
                'label_edit': 'cpsportlets_advanced_search_link_label',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': '',
                'css_class': '',
                'widget_mode_expr': '',
                'display_true': 'Yes',
                'display_false': 'No',
            },
        },
        'contextual_search_choice': {
            'type': 'CheckBox Widget',
            'data': {
                'title': '',
                'fields': ('contextual_search_choice',),
                'is_required': False,
                'label': '',
                'label_edit': 'cpsportlets_contextual_search_choice_label',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': "python: not context.getSearchFormParams()['contextual']",
                'css_class': '',
                'widget_mode_expr': '',
                'display_true': 'Yes',
                'display_false': 'No',
            },
        },
        'context_is_portlet': {
            'type': 'CheckBox Widget',
            'data': {
                'title': '',
                'fields': ('context_is_portlet',),
                'is_required': False,
                'label': '',
                'label_edit': 'cpsportlets_context_is_portlet_choice_label',
                'description': '',
                'help': '',
                'is_i18n': True,
                'readonly_layout_modes': (),
                'hidden_layout_modes': ('view',),
                'hidden_readonly_layout_modes': (),
                'hidden_empty': False,
                'hidden_if_expr': "not:context/contextual_search_choice",
                'css_class': '',
                'widget_mode_expr': '',
                'display_true': 'Yes',
                'display_false': 'No',
            },
        },
    },
    'layout': {
        'style_prefix': 'layout_portlet_',
        'flexible_widgets': (),
        'ncols': 1,
        'rows': [
            [{'widget_id': 'search', 'ncols': 1},
            ],
            [{'widget_id': 'contextual_search_choice', 'ncols': 1},
            ],
            [{'widget_id': 'context_is_portlet', 'ncols': 1},
            ],
            [{'widget_id': 'advanced_search_link', 'ncols': 1},
            ],
        ],
    },
}


layouts = {'search_portlet':search_portlet_layout}
return layouts
